# Generated by Django 5.0.3 on 2024-03-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wipscreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelentry',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reelentry',
            name='select_row_no',
            field=models.CharField(choices=[('Row 1', 'ROW 1'), ('Row 2', 'ROW 2'), ('Row 3', 'ROW 3'), ('Row 4', 'ROW 4'), ('Row 5', 'ROW 5')], max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='reelentry',
            name='select_slot_no',
            field=models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3'), ('Slot 4', 'Slot 4'), ('Slot 5', 'Slot 5'), ('Slot 6', 'Slot 6'), ('Slot 7', 'Slot 7'), ('Slot 8', 'Slot 8'), ('Slot 9', 'Slot 9'), ('Slot 10', 'Slot 10'), ('Slot 11', 'Slot 11'), ('Slot 12', 'Slot 12'), ('Slot 13', 'Slot 13'), ('Slot 14', 'Slot 14'), ('Slot 15', 'Slot 15'), ('Slot 16', 'Slot 16'), ('Slot 17', 'Slot 17'), ('Slot 18', 'Slot 18'), ('Slot 19', 'Slot 19'), ('Slot 20', 'Slot 20'), ('Slot 21', 'Slot 21'), ('Slot 22', 'Slot 22'), ('Slot 23', 'Slot 23'), ('Slot 24', 'Slot 24'), ('Slot 25', 'Slot 25'), ('Slot 26', 'Slot 26'), ('Slot 27', 'Slot 27'), ('Slot 28', 'Slot 28'), ('Slot 29', 'Slot 29'), ('Slot 30', 'Slot 30'), ('Slot 31', 'Slot 31'), ('Slot 32', 'Slot 32'), ('Slot 33', 'Slot 33'), ('Slot 34', 'Slot 34'), ('Slot 35', 'Slot 35'), ('Slot 36', 'Slot 36'), ('Slot 37', 'Slot 37'), ('Slot 38', 'Slot 38'), ('Slot 39', 'Slot 39'), ('Slot 40', 'Slot 40'), ('Slot 41', 'Slot 41'), ('Slot 42', 'Slot 42'), ('Slot 43', 'Slot 43'), ('Slot 44', 'Slot 44'), ('Slot 45', 'Slot 45'), ('Slot 46', 'Slot 46'), ('Slot 47', 'Slot 47'), ('Slot 48', 'Slot 48'), ('Slot 49', 'Slot 49'), ('Slot 50', 'Slot 50')], max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='reelentry',
            name='status',
            field=models.CharField(default='Empty', max_length=200, null=True),
        ),
    ]
