# Generated by Django 5.0.3 on 2024-03-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wipscreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reels',
            new_name='Reel',
        ),
    ]
